### ISSUE TITLE
Use -> as the animation seperator

### ISSUE THREAD

**Issue by aukgit** [aukgit/AnimateJs#1]
Use -> as the animation seperator

data-animate="bounce->delay(2)->repeat(2)->dur(2s)->selector(.this-one)->fadeIn->fadeOut->delay(2s)+zoomIn"
- iteration will be replaced with repeat.
- \+ means runs both animations simultaneously.
- () means method
- repeat(2) means repeat for 2 times
- repeat(always) means repeat infinite .

**Comment by Rashik004** [comment]
is it `selector(,this-one)` or `selector(.this-one)` ?

**Comment by Rashik004** [comment]
can there be multiple selectors like : `fade+zoomIn+bounce+otherEffects`?

**Comment by Rashik004** [comment]
what does `fadeOut->iteration(2)+zoomIn` means? 

A) fadeout and zooming will start simultaneously but **fading out will happen twice and zooming will happen once.**
B)fadeout and zooming will start simultaneously and **both of them will happen twice.**

also I'm confused about `fadeOut->delay(2s)+zoomIn->delay(5s)`

what would be the action here?

**Comment by aukgit** [comment]
**Q: is it selector(,this-one) or selector(.this-one) ?**
- selector(.this-one), and yes there could be multiple selectors.

**Q: can there be multiple selectors like : fade+zoomIn+bounce+otherEffects?**
- Yes

**Q: what does fadeOut->iteration(2)+zoomIn means?**
- it will be now fadeOut->repeat(2)+zoomIn, it will mean : fadeOut twice and start zoomin at the same time but it will only happens once(zoomin) since no modifier.

**Q: fadeOut->delay(2s)+zoomIn->delay(5s)**
- it means fadeOut after 2sec delay and then zoomIn will start after 5 sec of delay . So zoom in will run 7 sec delayed . Where in the previous question it runs simultaneously.
