### ISSUE TITLE
Code Organization 

### ISSUE THREAD

**Issue by Rashik004** [aukgit/AnimateJs#7]
As per my understanding, we've 4 main tasks:
1. extract the attribute
2. Manipulate DOM
3. Apply style
4. Inject the plugin 

I was thinking what if we make 4 seperate folders under the scripts folder for these tasks. Would it be easier to manage the code then or will it just increase overheads?

**Comment by aukgit** [comment]
Sure.. No problem. Separating those would be a great idea.

**Comment by aukgit** [comment]
If you understand the assigned tasks then you can close those or if you have further question you can ask more?
